Title = 'Cantor Project'

[db]
[db.mongo]
[db.mongo.main]
host = '192.168.1.3'
port = 27017
username = ''
password = ''

[db.redis]
[db.redis.main]
host = '192.168.1.3'
port = 6379

[db.mysql]
[db.mysql.main]
url = 'mysql+aiomysql://dev:123456@192.168.1.3:3306/cantor'
echo = false
pool_size = 10
max_overflow = 20
[db.mysql.main.connect_args]
connect_timeout = 10